name: Daily Knowledge Update
on:
  schedule:
    - cron: '0 0 * * *'  # 00:00 UTC daily
  workflow_dispatch:  # Manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scraper
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          echo "$GOOGLE_CREDS" > service-account.json
          python scraper.py
      - name: Commit changes
        run: |
          git config user.name 'Automated Update'
          git config user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Daily Q&A update"
          git push
