name: Daily Knowledge Update
on:
  schedule:
    - cron: '0 0 * * *'  # 12 AM UTC daily
  workflow_dispatch:  # Manual trigger option

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent infinite runs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all history for commits
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tenacity
          
      - name: Setup Google credentials
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          echo "$GOOGLE_CREDS" > service-account.json
          
      - name: Run scraper
        run: |
          python scraper.py
          
      - name: Check for changes
        id: changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Commit and push changes
        if: ${{ steps.changes.outputs.changes == 'true' }}
        run: |
          git config user.name "Automated Updater"
          git config user.email "actions@users.noreply.github.com"
          git commit -m "Auto: Daily Q&A Update"
          git push
          
      - name: Send success notification
        if: ${{ steps.changes.outputs.changes == 'true' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Daily Q&A update completed. Added new questions!"}' \
            $SLACK_WEBHOOK
            
      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: scraper-logs
          path: |
            scraper.log
            service-account.json
